info:
  build:
    name: "@project.name@"
    version: "@project.version@"
    buildTime: "@project.buildTime@"
    revision: "@git.commit.id@"


server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  jackson:
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      order-map-entries-by-keys: true
      write-dates-as-timestamps: false
